### PR TITLE
Adding Spain flag to flags.scss and spanish locale to i18n.js

### PR DESCRIPTION
**Pull request by FranLMSP**

### CODE REVIEW

**Comment by aocneanu** [comment]
to merge this you will have to make a [larger contribution](https://docs.laravel-enso.com/backend/localisation.html#contributing) :)

**Comment by FranLMSP** [comment]
what did i miss?

**Comment by aocneanu** [comment]
did you click the link in my reply?

**Comment by FranLMSP** [comment]
yes, and i followed the instructions for this and the other repos

**Comment by aocneanu** [comment]
Oh sorry mate, my bad

**Pull request merged**
