### PR TITLE
clean rtl

### PR DESCRIPTION
**Pull request by YacoubBelaoura**
a new approach that only use css

now enso by default is `LTR`
but when changing to an `RTL` lang it will add a `dir='rtl'` to the root div `#App`
this approach only use css to switch.
but there still the need for `isRTL` prop to change and keep track of the language used for changing `dir` attribute 

https://github.com/laravel-enso/Enso/pull/212#issue-267074216

### CODE REVIEW

**Comment by aocneanu** [comment]
Probably it would be best if we had a column in the languages table with a boolean `rtl` that will default to false.

In the AppState we could build a rtl array that will contain only the rtl lang keys. The array will be used by the theme selector.

We could add a state getter, `rtl`, that will default to false and will keep track of what mode we're in. And then we could map the getter in every `@enso-ui/core` component where it's required and use it on the component's root el like this `:rtl="rtl'`

Regarding the css, instead of using a `$directions` var and then an `each` / `if` / `else` let's use the direct selectors

for example this:

```scss
$directions : 'rtl' , 'ltr';
@each $dir in $directions {
    .footer {
        @if $dir == 'rtl' {
            [dir='#{$dir}'] & {
                margin-right: 180px;
                margin-left: unset;
            }
        } @else {
                margin-left: 180px;
        }
    }
```

vs this

```scss
.footer {
    &:dir(ltr) {
         margin-right: 180px;
         margin-left: unset;
     }
     &:dir(rtl) {
         margin-left: 180px;
     }
}
```

For the other packages like select etc we should add `rtl` as a prop, and where we have Enso wrappers, like the `EnsoSelect` we could pass the attribute directly from the state (vuex).

What do you think?

**Comment by YacoubBelaoura** [comment]
* for rtl column on the language table its a great idea,
* and there is only this array of language that are rtl.
```javascript
['ar', 'arc', 'dv', 'fa', 'ha', 'he', 'khw', 'ks', 'ku', 'ps', 'ur', 'yi']
```
* for the rtl prop, thats the first idea that i was going with, but i found that the user will need to define it on every component, and it will require a lot of refactoring to the current enso components, thats why i used this new approach, there will be no need for any other change to an existing project to add rtl support except adding  `dir` attribute to the root element.
* for the css, in this way there will be no default, the user will be obliged to add a `dir` attribute the root of that document, 
```css
.footer {
    &:dir(ltr) {
         margin-right: 180px;
         margin-left: unset;
     }
     &:dir(rtl) {
         margin-left: 180px;
     }
}
```
but here 
```css
$directions : 'rtl' , 'ltr';
@each $dir in $directions {
    .footer {
        @if $dir == 'rtl' {
            [dir='#{$dir}'] & {
                margin-right: 180px;
                margin-left: unset;
            }
        } @else {
                margin-left: 180px;
        }
    }
```
it will default to ltr. for project that don't need it. and they will not feel the change at all.

**Comment by aocneanu** [comment]
>for the rtl prop, thats the first idea that i was going with, but i found that the user will need to define it on every component, and it will require a lot of refactoring to the current enso components, thats why i used this new approach, there will be no need for any other change to an existing project to add rtl support except adding dir attribute to the root element.

But aren't we already modifying all the affected components (app, footer, bookmarks etc) by adding the new css in each of them?

We're looking for clean implementations, not easy ones. If we have to refactor 40 components then so be it.

**Comment by YacoubBelaoura** [comment]
* with this approach , i think there is no need for the rtl prop on the other component, there is only one use case that i can think of, is to force rtl so it will change direction. but its still dependent on bulma-rtl

and for css we can use this , with no default
 * no default 
 * support  IE -11
```css
        .footer {
            [dir='rtl'] & {
                margin-right: 0px;
            }
            [dir='ltr'] & {
                margin-left: 0px;
            }
        }
```
or this with default as ltr
* defaults to ltr
* no support for IE -11
```css
        .footer {
            margin-left: 0px;
            [dir='rtl'] & {
                margin-right: 0px;
                margin-left: unset;
            }
        }
```

**Comment by aocneanu** [comment]
This still feels hacky to me:

```css
.footer {
    margin-left: 0px;
    [dir='rtl'] & {
        margin-right: 0px;
        margin-left: unset;
    }
}
```

If I understand correctly, the only downside of using:

```css
.footer {
    [dir='rtl'] & {
        margin-right: 0px;
    }
    [dir='ltr'] & {
        margin-left: 0px;
    }
}
```

is that the devs that will use an Enso component outside Enso will have to set a `dir="ltr` or `dir="rtl"` on their root div?

If that's the case I don't see it such a big problem.

**Comment by YacoubBelaoura** [comment]
ok, i updated to the other approach. and on the other related components.

**Pull request merged**
